sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t hukam/gateway-app ./gateway
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$BUILD_VERSION
    docker tag hukam/gateway-app hukam/gateway-app:$TAG
    docker push hukam/gateway-app:$TAG
    docker push hukam/gateway-app
  fi
