sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset

# build image
- docker build -t hukam/gateway-app ./gateway
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV BUILD_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag hukam/gateway-app hukam/gateway-app:$BUILD_VERSION
    docker push hukam/gateway-app:$BUILD_VERSION
    docker push hukam/gateway-app
  fi

# build image
- docker build -t hukam/gateway-ui ./web
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV BUILD_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag hukam/gateway-ui hukam/gateway-ui:$BUILD_VERSION
    docker push hukam/gateway-ui:$BUILD_VERSION
    docker push hukam/gateway-ui
  fi