sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t hukam/gateway-ui ./web
# test image
- docker run --rm -ti hukam/gateway-ui -p 3000:4200 --version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV BUILD_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag hukam/gateway-ui hukam/gateway-ui:$TAG
    docker push hukam/gateway-ui:$TAG
    docker push hukam/gateway-ui
  fi
